# Generated by Django 3.1.1 on 2020-09-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.CharField(default='None', max_length=40),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.CharField(default='Hi', max_length=1000),
        ),
        migrations.AddField(
            model_name='article',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='My Title', max_length=30),
        ),
    ]
